export const ADD_BOOKMARKS = "ADD_BOOKMARKS";
export const ADD_BOOKMARKS_SUCCES = "ADD_BOOKMARKS_SUCCES";
export const ADD_BOOKMARKS_FAIL = "ADD_BOOKMARKS_FAIL";

export const GET_LIST_BOOKMARKS = "GET_LIST_BOOKMARKS";
export const GET_LIST_BOOKMARKS_SUCCES = "GET_LIST_BOOKMARKS_SUCCES";
export const GET_LIST_BOOKMARKS_FAIL = "GET_LIST_BOOKMARKS_FAIL";

export const DELETE_BOOKMARK = "DELETE_BOOKMARK";
export const DELETE_BOOKMARK_SUCCES = "DELETE_BOOKMARK_SUCCES";
export const DELETE_BOOKMARK_FAIL = "DELETE_BOOKMARK_FAIL";

export const UPDATE_BOOKMARK = "UPDATE_BOOKMARK";
export const UPDATE_BOOKMARK_SUCCES = "UPDATE_BOOKMARK_SUCCES";
export const UPDATE_BOOKMARK_FAIL = "UPDATE_BOOKMARK_FAIL";
